name: chat_wp
description: "Chats App PK like WhatsApp Theme. www.qrdpro.com"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2024.08.31+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^3.1.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0

  intl: ^0.18.0
  provider: ^6.1.2

  flutter_typeahead: ^5.2.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.1
  pdf: ^3.11.1
  printing: ^5.12.0
  rxdart: ^0.27.0
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
